### ISSUE TITLE
How stable does Arduino and Android work for you?

### ISSUE THREAD

**Issue by thaussma** [palazzem/adk-toolkit#18]
Hi,
for some hours I'm trying to connect my Android phones with my Arduino Mega ADK. I tried this library too, but regardless what I did, the results are very unstable.

I saw the example sketch in this repo. 
- Which USB-Host library are you using? I cannot compile it because the USB-Host lib that I use does not have those `read` and `write` methods.
- How reliable does the connection between Android and Arduino work for you?
- Do you have some tips or a more complete example that works for you?
###### Nexus 6

My Nexus 6 seems not recognise the Arduino. 
- The intent filter in the AndroidManifest.xml seems not to work, the app is not started.
- `UsbManager#getAccessoryList()` does not return results
- `Adk#isReady()` returns always false

Just once the Android App was started when I connected the phone with the board and I could send and receive data. But after that it did never work again. I can see a 'USB device connected' notification for some seconds but nothing else happens.
###### Galaxy Nexus

My Galaxy Nexus works better. Very often the usb connection works and I can send and receive. 
- I have to press the reset button on Arduino and reconnect the phone several times to establish a connection
- After Killing the Android app and restarting it the connection does not work again
#### My setup:
- Example (Arduino sketch and Android app) that I'm using [ArduinoBlinkLED](https://github.com/Lauszus/ArduinoBlinkLED)
- [USB-Host-Shield-20](http://platformio.org/#!/lib/show/59/USB-Host-Shield-20)
- Arduino Mega ADK
- Galaxy Nexus with Cyanogen 11 (Android 4.4.4)
- Nexus 6 with stock ROM, Android 5.1.1

**Comment by thaussma** [comment]
I did never got the [USB-Host-Shield-20](http://platformio.org/#!/lib/show/59/USB-Host-Shield-20) working correctly on my Arduino megaADK. Instead I am using [this library](https://github.com/thaussma/aoa2011) - works nice so far.

**Comment by palazzem** [comment]
Hi @thaussma, sorry for the huge delay :)

About your question related to the communication between Arduino (ADK-friendly) and Android, I can say that it's "pretty stable". What I mean is that the communication works fine but having a working prototype that is more complex than a toy project or a hobby project, is pretty tricky.

> Which USB-Host library are you using? I cannot compile it because the USB-Host lib that I use does not have those read and write methods.

The header I'm using in sketches is `<adk.h>` which is available in the library set of Arduino IDE 1.5.8 Beta but NOT in the latest version of the IDE (1.6.7 at the moment). I assume they've dropped the support because of two main reasons:
1. the Arduino Mega ADK [has been retired](https://www.arduino.cc/en/Main/ArduinoBoardMegaADK) from the market
2. Google doesn't update the ADK / AOA protocol since 2011. Obviously they didn't find any interest in further development.

> Do you have some tips or a more complete example that works for you?

Yes, you can find a fully working example (used by other developers during workshops and training) in the following URLs:
- https://github.com/palazzem/android-udoo-rover (Android part)
- https://github.com/palazzem/arduino-udoo-rover (Arduino part; skip the complexity of motors controller)

A tip about the development of Android <-> Arduino is that you should put many efforts in the initial stage because, unfortunately, the system doesn't work properly out of the box. It was the same for me.

> My Nexus 6 seems not recognise the Arduino

I'm sorry but I don't have any experience with ADK/AOA communication in a Nexus 6. If it doesn't work, probably, means that the N6 is not a supported device and doesn't have the proper C/C++ bindings under the hood. This means that the Java SDK still have the ADK/AOA support while the low level library (or the hardware itself) doesn't support this protocol anymore.

> My Galaxy Nexus works better. Very often the usb connection works and I can send and receive.
> 
> I have to press the reset button on Arduino and reconnect the phone several times to establish a connection
> After Killing the Android app and restarting it the connection does not work again

This issue happens to me many times. Just check if your case is the same described in a [previous issue](https://github.com/palazzem/adk-toolkit/issues/11). The "solution" was to avoid the ADK `close()` method because of a bug in the ADK itself.

I don't know if this comment is helping you. Let me know if you need more info.

**Comment by thaussma** [comment]
I assume you use a Arduino Due? AFAIK the accessory implementation in Arduino 1.5.8 is only for those devices. 
The old USB-HostLibrary with googles ADK 2011 does work quite stable, with a few changes.

**Comment by palazzem** [comment]
Yes, it was a board based on an Arduino Due (UDOO board).
If everything works fine for you, I'll proceed closing this issue.

Thank you for sharing your experience with ADK devices :)

**Comment by ramast** [comment]
In case someone else encountered this problem:

According to adk documentation
https://developer.android.com/guide/topics/connectivity/usb/accessory.html

Your application MUST obtain permission from user (by calling `requestPermission()`) before you can use the connected accessory.
Alternatively, You can use an intent filter (as described in this repo's README file) to discover accessories as they're connected, it automatically receives permission if the user allows your application to handle the intent. If not, you must request permission explicitly in your application before connecting to the accessory.

Hope that helps.
